name: hirome_rental_center_web
description: ひろめ市場 食器レンタルシステム - 食器センター専用

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  modal_bottom_sheet: ^3.0.0
  top_snackbar_flutter: ^3.1.0
  calendar_date_picker2: ^1.1.5
  month_picker_dialog: ^4.0.1
  csv: ^6.0.0
  badges: ^3.1.2
  printing: ^5.13.1
  assets_audio_player: ^3.1.1
  touchable: ^1.0.2
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_messaging: ^15.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/sounds/

  fonts:
    - family: SourceHanSansJP-Bold
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
    - family: SourceHanSansJP-Regular
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Regular.otf